language: node_js

node_js:
  - "12.3.1"

services:
  - docker
  
install:
  - npm install

script: 
  - npm test

after_success:
  - docker build -t $DOCKER_IMAGE .

deploy:
  provider: script
  script: .docker/publish.sh
  on:
    branch: master