language: node_js

node_js:
  - lts/*

services:
  - docker

install:
  - npm install --progress=false

script:
  - npm test

after_success:
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_TESTNET_SCW
    --build-arg LCD_URL=${ALMERICO_LCD_URL}
    --build-arg WS_URL=${ALMERICO_WS_URL}
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST}"
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE}"
    .
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_DEVNET_SCW
    --build-arg LCD_URL=${ALMERICO_DEVNET_LCD_URL}
    --build-arg WS_URL=${ALMERICO_DEVNET_WS_URL}
    --build-arg ANCESTORS_LIST="${ALMERICO_DEVNET_ANCESTORS_LIST}"
    --build-arg MAIN_TITLE="${ALMERICO_DEVNET_MAIN_TITLE}"
    .
  - test $TRAVIS_TAG && docker build -t $DOCKER_IMAGE_MAINNET_SCW
    --build-arg LCD_URL=${ALMERICO_MAINNET_LCD_URL}
    --build-arg WS_URL=${ALMERICO_MAINNET_WS_URL}
    --build-arg ANCESTORS_LIST="${ALMERICO_MAINNET_ANCESTORS_LIST}"
    --build-arg MAIN_TITLE="${ALMERICO_MAINNET_MAIN_TITLE}"
    .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash docker_push_dev.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: bash docker_push_latest.sh
    on:
      tags: true
