language: node_js

node_js:
  - lts/*

services:
  - docker

install:
  - npm install --progress=false

script:
  - npm test

after_success:
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_TESTNET
    --build-arg LCD_URL=${ALMERICO_LCD_URL_TESTNET}
    --build-arg WS_URL=${ALMERICO_WS_URL_TESTNET}
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_TESTNET}"
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_TESTNET}"
    .
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_DEVNET
    --build-arg LCD_URL=${ALMERICO_LCD_URL_DEVNET}
    --build-arg WS_URL=${ALMERICO_WS_URL_DEVNET}
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_DEVNET}"
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_DEVNET}"
    .
  - test $TRAVIS_BRANCH = "master" && docker build -t $DOCKER_IMAGE_MAINNET
    --build-arg LCD_URL=${ALMERICO_LCD_URL_MAINNET}
    --build-arg WS_URL=${ALMERICO_WS_URL_MAINNET}
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_MAINNET}"
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_MAINNET}"
    .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash docker_push_dev.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: bash docker_push_latest.sh
    on:
      branch: master
