language: node_js

node_js:
  - "13.5.0"

services:
  - docker
  
install:
  - npm install

script: 
  - npm test

after_success:
  - docker build -t $DOCKER_IMAGE
    --build-arg LCD_URL=${ALMERICO_LCD_URL}
    --build-arg RPC_URL=${ALMERICO_RPC_URL}
    --build-arg WS_URL=${ALMERICO_WS_URL}
    --build-arg API_VERSION=${ALMERICO_API_VERSION}
    .

deploy:
  provider: script
  script: docker push $DOCKER_IMAGE
  on:
    branch: development