language: node_js

node_js:
  - lts/*

services:
  - docker

before_script:
  - bash ./scripts/docker_check_vars.sh

install:
  - npm install -s --no-audit --no-fund

script:
  - npm run test

branches:
  except:
    - /^wip\/.*/

after_success:
  - test $TRAVIS_BRANCH = "master" && docker build -t $DOCKER_IMAGE_MAINNET
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_MAINNET}"
    --build-arg API_VERSION=${ALMERICO_API_VERSION_MAINNET}
    --build-arg BLOCKS_MONITOR="${ALMERICO_BLOCKS_MONITOR_MAINNET}"
    --build-arg FIRST_CONVERSION_RATE=${ALMERICO_FIRST_CONVERSION_RATE_MAINNET}
    --build-arg FIRST_HEIGHT=${ALMERICO_FIRST_HEIGHT_MAINNET}
    --build-arg LCD_URL=${ALMERICO_LCD_URL_MAINNET}
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_MAINNET}"
    --build-arg MINTER_ACCOUNT="${ALMERICO_MINTER_ACCOUNT_MAINNET}"
    --build-arg SPREADSHEET_ACCOUNTS="${ALMERICO_SPREADSHEET_ACCOUNTS_MAINNET}"
    --build-arg WS_URL=${ALMERICO_WS_URL_MAINNET}
    .
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_TESTNET
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_TESTNET}"
    --build-arg API_VERSION=${ALMERICO_API_VERSION_TESTNET}
    --build-arg BLOCKS_MONITOR="${ALMERICO_BLOCKS_MONITOR_TESTNET}"
    --build-arg FIRST_CONVERSION_RATE=${ALMERICO_FIRST_CONVERSION_RATE_TESTNET}
    --build-arg FIRST_HEIGHT=${ALMERICO_FIRST_HEIGHT_TESTNET}
    --build-arg LCD_URL=${ALMERICO_LCD_URL_TESTNET}
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_TESTNET}"
    --build-arg MINTER_ACCOUNT="${ALMERICO_MINTER_ACCOUNT_TESTNET}"
    --build-arg SPREADSHEET_ACCOUNTS="${ALMERICO_SPREADSHEET_ACCOUNTS_TESTNET}"
    --build-arg WS_URL=${ALMERICO_WS_URL_TESTNET}
    .
  - test $TRAVIS_BRANCH = "development" && docker build -t $DOCKER_IMAGE_DEVNET
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_DEVNET}"
    --build-arg API_VERSION=${ALMERICO_API_VERSION_DEVNET}
    --build-arg BLOCKS_MONITOR="${ALMERICO_BLOCKS_MONITOR_DEVNET}"
    --build-arg FIRST_CONVERSION_RATE=${ALMERICO_FIRST_CONVERSION_RATE_DEVNET}
    --build-arg FIRST_HEIGHT=${ALMERICO_FIRST_HEIGHT_DEVNET}
    --build-arg LCD_URL=${ALMERICO_LCD_URL_DEVNET}
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_DEVNET}"
    --build-arg MINTER_ACCOUNT="${ALMERICO_MINTER_ACCOUNT_DEVNET}"
    --build-arg SPREADSHEET_ACCOUNTS="${ALMERICO_SPREADSHEET_ACCOUNTS_DEVNET}"
    --build-arg WS_URL=${ALMERICO_WS_URL_DEVNET}
    .
  - test $TRAVIS_BRANCH = "alfa" && docker build -t $DOCKER_IMAGE_TESTNET_V3
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_TESTNET}"
    --build-arg API_VERSION=${ALMERICO_API_VERSION_TESTNET}
    --build-arg BLOCKS_MONITOR="${ALMERICO_BLOCKS_MONITOR_TESTNET}"
    --build-arg FIRST_CONVERSION_RATE=${ALMERICO_FIRST_CONVERSION_RATE_TESTNET}
    --build-arg FIRST_HEIGHT=${ALMERICO_FIRST_HEIGHT_TESTNET}
    --build-arg LCD_URL=${ALMERICO_LCD_URL_TESTNET}
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_TESTNET}"
    --build-arg MINTER_ACCOUNT="${ALMERICO_MINTER_ACCOUNT_TESTNET}"
    --build-arg SPREADSHEET_ACCOUNTS="${ALMERICO_SPREADSHEET_ACCOUNTS_TESTNET}"
    --build-arg WS_URL=${ALMERICO_WS_URL_TESTNET}
    .
  - test $TRAVIS_BRANCH = "alfa" && docker build -t $DOCKER_IMAGE_ALFANET
    --build-arg ANCESTORS_LIST="${ALMERICO_ANCESTORS_LIST_DEVNET}"
    --build-arg API_VERSION=${ALMERICO_API_VERSION_DEVNET}
    --build-arg BLOCKS_MONITOR="${ALMERICO_BLOCKS_MONITOR_ALFANET}"
    --build-arg FIRST_CONVERSION_RATE=${ALMERICO_FIRST_CONVERSION_RATE_DEVNET}
    --build-arg FIRST_HEIGHT=${ALMERICO_FIRST_HEIGHT_DEVNET}
    --build-arg LCD_URL=${ALMERICO_LCD_URL_DEVNET}
    --build-arg MAIN_TITLE="${ALMERICO_MAIN_TITLE_ALFANET}"
    --build-arg MINTER_ACCOUNT="${ALMERICO_MINTER_ACCOUNT_DEVNET}"
    --build-arg SPREADSHEET_ACCOUNTS="${ALMERICO_SPREADSHEET_ACCOUNTS_DEVNET}"
    --build-arg WS_URL=${ALMERICO_WS_URL_DEVNET}
    .

deploy:
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/docker_push_dev.sh
    on:
      branch: development
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/docker_push_latest.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: bash ./scripts/docker_push_alfa.sh
    on:
      branch: alfa
