export const PROPOSALS = {
  STATUS: {
    DEPOSIT_PERIOD: 'PROPOSAL_STATUS_DEPOSIT_PERIOD',
    FAILED: 'PROPOSAL_STATUS_FAILED',
    PASSED: 'PROPOSAL_STATUS_PASSED',
    REJECTED: 'PROPOSAL_STATUS_REJECTED',
    UNSPECIFIED: 'PROPOSAL_STATUS_UNSPECIFIED',
    VOTING_PERIOD: 'PROPOSAL_STATUS_VOTING_PERIOD',
  },
};
