export const ROUTES = {
  NAME: {
    NOT_FOUND: 'notFound',
    ACCOUNT: 'account',
    BLOCKS: 'blocks',
    BLOCKS_LIST: 'blocksList',
    BLOCKS_DETAIL: 'blocksDetail',
    HOME: 'home',
    EXCHANGE_RATE: 'exchangeRate',
    TRANSACTIONS: 'transactions',
    TRANSACTIONS_LIST: 'transactionsList',
    TRANSACTIONS_DETAIL: 'transactionsDetail',
    TRANSACTIONS_SHAREDOC: 'transactionsSharedoc',
    VALIDATORS: 'validators',
    VALIDATORS_LIST: 'validatorsList',
    VALIDATORS_DETAIL: 'validatorsDetail',
  },
  PATH: {
    ROOT: '/',
    NOT_FOUND: '/404',
    ACCOUNT: '/account/:id',
    BLOCKS: '/blocks',
    BLOCKS_LIST: 'list',
    BLOCKS_DETAIL: 'detail/:id',
    HOME: '/home',
    EXCHANGE_RATE: '/exchange-rate',
    TRANSACTIONS: '/transactions',
    TRANSACTIONS_LIST: 'list',
    TRANSACTIONS_DETAIL: 'detail/:id',
    TRANSACTIONS_SHAREDOC: 'sharedoc/:hash/uuid/:uuid',
    VALIDATORS: '/validators',
    VALIDATORS_LIST: 'list',
    VALIDATORS_DETAIL: 'detail/:id',
  },
  TITLE: {
    NOT_FOUND: 'Not Found',
    ACCOUNT: 'Account',
    BLOCKS: 'Blocks',
    BLOCKS_LIST: 'Blocks List',
    BLOCKS_DETAIL: 'Blocks Detail',
    HOME: 'Home',
    EXCHANGE_RATE: 'Exchange Rate',
    TRANSACTIONS: 'Transactions',
    TRANSACTIONS_LIST: 'Transactions List',
    TRANSACTIONS_DETAIL: 'Transactions Detail',
    TRANSACTIONS_SHAREDOC: 'Transactions Sharedoc',
    VALIDATORS: 'Validators',
    VALIDATORS_LIST: 'Validators List',
    VALIDATORS_DETAIL: 'Validators Detail',
  },
};
