#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
echo "Publishing release $DOCKER_IMAGE_ALMERICO_MAINNET from $TRAVIS_BRANCH branch"
docker tag $DOCKER_IMAGE_ALMERICO_MAINNET $DOCKER_IMAGE_ALMERICO_MAINNET 
docker push $DOCKER_IMAGE_ALMERICO_MAINNET
echo "Publishing release $DOCKER_IMAGE_ALMERICO_LATEST from $TRAVIS_BRANCH branch"
docker tag $DOCKER_IMAGE_ALMERICO_MAINNET $DOCKER_IMAGE_ALMERICO_LATEST
docker push $DOCKER_IMAGE_ALMERICO_LATEST
