VARS=("ALMERICO_ANCESTORS_LIST_DEVNET" "ALMERICO_ANCESTORS_LIST_MAINNET" "ALMERICO_ANCESTORS_LIST_TESTNET" "ALMERICO_API_VERSION_DEVNET" "ALMERICO_API_VERSION_MAINNET" "ALMERICO_API_VERSION_TESTNET" "ALMERICO_BLOCKS_MONITOR_DEVNET" "ALMERICO_BLOCKS_MONITOR_MAINNET" "ALMERICO_BLOCKS_MONITOR_TESTNET" "ALMERICO_FIRST_CONVERSION_RATE_DEVNET" "ALMERICO_FIRST_CONVERSION_RATE_MAINNET" "ALMERICO_FIRST_CONVERSION_RATE_TESTNET" "ALMERICO_FIRST_HEIGHT_DEVNET"  "ALMERICO_FIRST_HEIGHT_MAINNET" "ALMERICO_FIRST_HEIGHT_TESTNET" "ALMERICO_LCD_URL_DEVNET" "ALMERICO_LCD_URL_MAINNET" "ALMERICO_LCD_URL_TESTNET" "ALMERICO_MAIN_TITLE_DEVNET" "ALMERICO_MAIN_TITLE_MAINNET" "ALMERICO_MAIN_TITLE_TESTNET" "ALMERICO_MINTER_ACCOUNT_DEVNET" "ALMERICO_MINTER_ACCOUNT_MAINNET" "ALMERICO_MINTER_ACCOUNT_TESTNET" "ALMERICO_SPREADSHEET_ACCOUNTS_DEVNET" "ALMERICO_SPREADSHEET_ACCOUNTS_MAINNET" "ALMERICO_SPREADSHEET_ACCOUNTS_TESTNET" "ALMERICO_WS_URL_DEVNET" "ALMERICO_WS_URL_MAINNET" "ALMERICO_WS_URL_TESTNET")

echo "Variables control in progress..."
for variable in "${VARS[@]}"; do
    if ! [[ -v $variable ]]; then
        echo "Undefined $variable" 1>&2
        exit 1
    fi
done
echo "Completed variables control"