#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin "$DOCKER_REGISTRY"
echo $(docker images)
docker tag $DOCKER_IMAGE_ALMERICO_MAINNET $DOCKER_IMAGE_ALMERICO_MAINNET 
docker tag $DOCKER_IMAGE_ALMERICO_MAINNET $DOCKER_IMAGE_ALMERICO_LATEST
docker push $DOCKER_IMAGE_ALMERICO_MAINNET 
docker push $DOCKER_IMAGE_ALMERICO_LATEST
