export default {
  abrTokens: (state) => state.abrTokens,
  conversionRate: (state) => state.conversionRate,
  error: (state) => state.error,
  isLoading: (state) => state.isLoading,
  isLoadingTxs: (state) => state.isLoadingTxs,
  pool: (state) => state.pool,
  rateUpdates: (state) => state.rateUpdates,
  rateUpdatesOffset: (state) => state.rateUpdatesOffset,
  rateUpdatesPagination: (state) => state.rateUpdatesPagination,
  rateUpdatesTotal: (state) => state.rateUpdatesPagination.total,
  startingDate: (state) => state.startingDate,
  supply: (state) => state.supply,
  transactions: (state) => state.transactions,
  txEventHeight: (state) => state.txEventHeight,
  vbrTokens: (state) => state.vbrTokens,
};
