name: CI/CD Pipeline

run-name: ${{ github.actor }} is running ${{ github.workflow }} on ${{ github.ref_name }}

on:
  push:
    branches-ignore:
      - 'alfa'
      - 'development'
      - 'master'
      - 'bck**'
      - 'bug**'
      - 'wip**'

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/wf-build-test.yml
