name: CI/CD Pipeline - Master Branch

run-name: ${{ github.actor }} is building the Mainnet Explorer from ${{ github.ref_name }}

env:
  ANCESTORS_LIST: ${{ vars.ALMERICO_MAINNET_ANCESTORS_LIST }}
  API_VERSION: ${{ vars.ALMERICO_MAINNET_API_VERSION }}
  API_VERSION_COSMWASM: ${{ vars.ALMERICO_MAINNET_API_VERSION_COSMWASM }}
  BACKEND: ${{ vars.ALMERICO_MAINNET_BACKEND }}
  BACKEND_WS: ${{ vars.ALMERICO_MAINNET_BACKEND_WS }}
  FIRST_CONVERSION_RATE: ${{ vars.ALMERICO_MAINNET_FIRST_CONVERSION_RATE }}
  FIRST_HEIGHT: ${{ vars.ALMERICO_MAINNET_FIRST_HEIGHT }}
  LCD_URL: ${{ vars.ALMERICO_MAINNET_LCD_URL }}
  MAIN_TITLE: ${{ vars.ALMERICO_MAINNET_MAIN_TITLE }}
  WASM_CW20_CODE_ID: ${{ vars.ALMERICO_MAINNET_WASM_CW20_CODE_ID }}
  WASM_SWAP_CODE_ID: ${{ vars.ALMERICO_MAINNET_WASM_SWAP_CODE_ID }}
  WS_URL: ${{ vars.ALMERICO_MAINNET_WS_URL }}

on:
  push:
    branches:
      - 'master'

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/wf-build-test.yml

  deploy-docker-image-mainnet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify Environment Variables
        run: |
          if "${{ env.ANCESTORS_LIST }}" == "" || "${{ env.API_VERSION }}" == "" || "${{ env.API_VERSION_COSMWASM }}" == "" || "${{ env.BACKEND }}" == "" || "${{ env.BACKEND_WS }}" == "" || "${{ env.FIRST_CONVERSION_RATE }}" == "" || "${{ env.FIRST_HEIGHT }}" == "" || "${{ env.LCD_URL }}" == "" || "${{ env.MAIN_TITLE }}" == "" || "${{ env.WASM_CW20_CODE_ID }}" == "" || "${{ env.WASM_SWAP_CODE_ID }}" == "" || "${{ env.WS_URL }}" == ""; then
            echo "Error: Environment variables are not set."
            exit 1
          fi

      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v3

      - name: Login To Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_IMAGE }}:latest
            ${{ secrets.DOCKER_IMAGE }}:mainnet
          build-args: |
            ANCESTORS_LIST=${{ env.ANCESTORS_LIST }}
            API_VERSION=${{ env.API_VERSION }}
            API_VERSION_COSMWASM=${{ env.API_VERSION_COSMWASM }}
            BACKEND=${{ env.BACKEND }}
            BACKEND_API_VERSION=${{ env.BACKEND_API_VERSION }}
            BACKEND_WS=${{ env.BACKEND_WS }}
            FIRST_CONVERSION_RATE=${{ env.FIRST_CONVERSION_RATE }}
            FIRST_HEIGHT=${{ env.FIRST_HEIGHT }}
            LCD_URL=${{ env.LCD_URL }}
            MAIN_TITLE=${{ env.MAIN_TITLE }}
            WASM_CW20_CODE_ID=${{ env.WASM_CW20_CODE_ID }}
            WASM_SWAP_CODE_ID=${{ env.WASM_SWAP_CODE_ID }}
            WS_URL=${{ env.WS_URL }}
