name: CI/CD Pipeline - Alfa Branch

run-name: ${{ github.actor }} is building the Devnet Explorer from ${{ github.ref_name }}

env:
  ANCESTORS_LIST: ${{ vars.ALMERICO_DEVNET_ANCESTORS_LIST }}
  API_VERSION: ${{ vars.ALMERICO_DEVNET_API_VERSION }}
  API_VERSION_COSMWASM: ${{ vars.ALMERICO_DEVNET_API_VERSION_COSMWASM }}
  BACKEND: ${{ vars.ALMERICO_DEVNET_BACKEND }}
  BACKEND_API_VERSION: ${{ vars.ALMERICO_DEVNET_BACKEND_API_VERSION }}
  BACKEND_WS: ${{ vars.ALMERICO_DEVNET_BACKEND_WS }}
  FIRST_CONVERSION_RATE: ${{ vars.ALMERICO_DEVNET_FIRST_CONVERSION_RATE }}
  FIRST_HEIGHT: ${{ vars.ALMERICO_DEVNET_FIRST_HEIGHT }}
  LCD_URL: ${{ vars.ALMERICO_DEVNET_LCD_URL }}
  MAIN_TITLE: ${{ vars.ALMERICO_DEVNET_MAIN_TITLE }}
  WASM_CW20_CODE_ID: ${{ vars.ALMERICO_DEVNET_WASM_CW20_CODE_ID }}
  WASM_SWAP_CODE_ID: ${{ vars.ALMERICO_DEVNET_WASM_SWAP_CODE_ID }}
  WS_URL: ${{ vars.ALMERICO_DEVNET_WS_URL }}

on:
  push:
    branches:
      - 'alfa'

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/wf-build-test.yml

  call-workflow-deploy-docker-image:
    env:
      DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}:devnet

    uses: ./.github/workflows/wf-deploy-docker-image.yml
