name: CI/CD Pipeline - Development Branch

run-name: ${{ github.actor }} is building the Testnet Explorer from ${{ github.ref_name }}

env:
  ANCESTORS_LIST: ${{ vars.ALMERICO_TESTNET_ANCESTORS_LIST }}
  API_VERSION: ${{ vars.ALMERICO_TESTNET_API_VERSION }}
  API_VERSION_COSMWASM: ${{ vars.ALMERICO_TESTNET_API_VERSION_COSMWASM }}
  BACKEND: ${{ vars.ALMERICO_TESTNET_BACKEND }}
  BACKEND_API_VERSION: ${{ vars.ALMERICO_TESTNET_BACKEND_API_VERSION }}
  BACKEND_WS: ${{ vars.ALMERICO_TESTNET_BACKEND_WS }}
  FIRST_CONVERSION_RATE: ${{ vars.ALMERICO_TESTNET_FIRST_CONVERSION_RATE }}
  FIRST_HEIGHT: ${{ vars.ALMERICO_TESTNET_FIRST_HEIGHT }}
  LCD_URL: ${{ vars.ALMERICO_TESTNET_LCD_URL }}
  MAIN_TITLE: ${{ vars.ALMERICO_TESTNET_MAIN_TITLE }}
  WASM_CW20_CODE_ID: ${{ vars.ALMERICO_TESTNET_WASM_CW20_CODE_ID }}
  WASM_SWAP_CODE_ID: ${{ vars.ALMERICO_TESTNET_WASM_SWAP_CODE_ID }}
  WS_URL: ${{ vars.ALMERICO_TESTNET_WS_URL }}
  DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}:testnet

on:
  push:
    branches:
      - 'development'

jobs:
  call-workflow-build-and-test:
    uses: ./.github/workflows/wf-build-test.yml

  call-workflow-deploy-docker-image:
    uses: ./.github/workflows/wf-deploy-docker-image.yml
